# Generated by Django 4.2 on 2024-04-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tilte',
            new_name='title',
        ),
    ]
